projects = (
    {
        "name": "BCI Framework",
        "type": "Desktop application",
        "type_es": "Aplicación de escritorio",
        "description": "A distributed processing tool, stimuli delivery, psychophysiological experiments designer and real-time data visualizations for OpenBCI.",
        "description_es": "Una herramienta de procesamiento distribuido, entrega de estímulos, diseño de experimentos psicofisiológicos y visualización de datos en tiempo real para OpenBCI.",
        "tools": ["Python", "PySide", "OpenBCI", "Kafka", "GNU/Linux"],
        "documentation": "https://bci-framework.readthedocs.io",
        "repository": "https://github.com/dunderlab/bci-framework",
        "logo": "https://bci-framework.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2021",
    },
    {
        "name": "OpenBCI Stream",
        "type": "Hardware drivers",
        "type_es": "Controladores de hardware",
        "description": "High level Python module for EEG/EMG/ECG acquisition and distributed streaming for OpenBCI Cyton board.",
        "description_es": "Módulo Python de alto nivel para adquisición de EEG/EMG/ECG y transmisión distribuida para la tarjeta OpenBCI Cyton.",
        "tools": ["Python", "OpenBCI", "Kafka", "GNU/Linux", "Raspberry Pi"],
        "documentation": "https://openbci-stream.readthedocs.io/",
        "repository": "https://github.com/dunderlab/openbci-stream",
        "logo": "https://openbci-stream.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2019",
    },
    {
        "name": "Qt Material",
        "type": "GUI theme",
        "type_es": "Tema gráfico",
        "description": "This is another stylesheet for PySide6, PySide2, PyQt5 and PyQt6, which looks like Material Design (close enough).",
        "description_es": "Otro conjunto de estilos para PySide6, PySide2, PyQt5 y PyQt6, con aspecto similar a Material Design.",
        "tools": ["Python", "OpenBCI", "Kafka", "GNU/Linux", "Raspberry Pi"],
        "documentation": "https://qt-material.readthedocs.io/",
        "repository": "https://github.com/dunderlab/qt-material",
        "logo": "https://qt-material.readthedocs.io/en/latest/_static/logo.png",
        "year": "2019",
    },
    {
        "name": "Radiant Framework",
        "type": "Web apps development framework",
        "type_es": "Framework para desarrollo de aplicaciones web",
        "description": "A novel web framework designed to leverage the capabilities of Brython, a browser-based Python implementation. This innovative approach allows developers to write web applications entirely in Python, bypassing the conventional requirements of HTML, CSS, or JavaScript for frontend development.",
        "description_es": "Un novedoso framework web basado en Brython, permitiendo escribir aplicaciones web completamente en Python, sin necesidad de HTML, CSS o JavaScript para el desarrollo frontend.",
        "tools": ["Python", "Brython", "Tornado"],
        "documentation": "https://radiant-framework.readthedocs.io",
        "repository": "https://github.com/dunderlab/python-radiant_framework",
        "logo": "https://radiant-framework.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2023",
    },
    {
        "name": "Radiant Compiler",
        "type": "Android APK generator",
        "type_es": "Generador de APKs para Android",
        "description": "A tool designed for compiling Brighton and Django applications into Android packages (APKs), providing a streamlined and efficient process to convert these Python-based applications into a format that is compatible and installable on Android devices.",
        "description_es": "Herramienta para compilar aplicaciones de Brighton y Django en paquetes APK de Android, facilitando la distribución de aplicaciones Python en dispositivos Android.",
        "tools": ["Python", "Python-for-Android", "Django", "Android", "Docker"],
        "documentation": "https://radiant-compiler.readthedocs.io/",
        "repository": "https://github.com/dunderlab/python-radiant_compiler",
        "logo": "https://radiant-compiler.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2023",
    },
    {
        "name": "DunderLab’s Documentation Guide",
        "type": "Python module",
        "type_es": "Módulo de Python",
        "description": "This Python module facilitates the creation of Sphinx Documentation directly from Jupyter Notebooks. Essentially, it provides a preconfigured environment that utilizes nbsphinx in the background, complete with custom styles and preloaded modules.",
        "description_es": "Este módulo de Python facilita la creación de documentación Sphinx directamente desde Notebooks de Jupyter, proporcionando un entorno preconfigurado que utiliza nbsphinx y estilos personalizados.",
        "tools": ["Python", "Sphinx"],
        "documentation": "https://dunderlab-docs.readthedocs.io/",
        "repository": "https://github.com/dunderlab/python-dunderlab.docs",
        "logo": "https://dunderlab-docs.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2023",
    },
    {
        "name": "TimeScaleDB App",
        "type": "Django application",
        "type_es": "Aplicación Django",
        "description": "A Django-based web application that provides an API for managing and querying time-series data. This application utilizes RealTimeDB, a time-series database built atop PostgreSQL, for efficient storage and analysis of time-series data. With custom pagination classes and viewsets, the TimeScaleDB App delivers a powerful and flexible way to interact with Source, Measure, Channel, and TimeSerie models.",
        "description_es": "Aplicación web basada en Django que ofrece una API para gestionar y consultar datos series temporales utilizando RealTimeDB y PostgreSQL. Incluye clases de paginación y viewsets personalizados para interactuar eficientemente con modelos de series temporales.",
        "tools": ["Python", "Django", "TimeScaleDB", "PostgreSQL"],
        "documentation": "https://timescaledb-app.readthedocs.io/",
        "repository": "https://github.com/dunderlab/python-django-timescaledbapp",
        "logo": "https://timescaledb-app.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2023",
    },
    # ============================
    # NUEVOS PROYECTOS UNIFICADOS
    # ============================
    {
        "name": "CtenoLab",
        "type": "Web application",
        "type_es": "Aplicación web",
        "description": "CtenoLab enables EEG and BCI paradigms directly in the browser with real-time hardware synchronization and WebUSB/WebSerial integration.",
        "description_es": "CtenoLab permite paradigmas EEG y BCI directamente en el navegador, con sincronización de hardware en tiempo real e integración de WebUSB/WebSerial.",
        "tools": ["Angular", "WebUSB", "WebSerial"],
        "documentation": "",
        "repository": "",
        "logo": "/root/assets/images/cteno_logo.png",
        "page": "https://ctenolab.com",
        "year": "2025",
    },
    {
        "name": "Chaski Confluent",
        "type": "Python module",
        "type_es": "Módulo de Python",
        "description": "Asynchronous messaging, node discovery and remote method invocation for distributed systems.",
        "description_es": "Mensajería asíncrona, descubrimiento de nodos e invocación remota de métodos para sistemas distribuidos.",
        "tools": ["Python"],
        "documentation": "https://chaski-confluent.readthedocs.io/en/latest/",
        "repository": "https://github.com/dunderlab/python-chaski",
        "logo": "https://chaski-confluent.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2024",
    },
    {
        "name": "Dunderlab - visualizations",
        "type": "Python module",
        "type_es": "Módulo de Python",
        "description": "Tools for brain connectivity visualization, topoplots and EEG processing (Matplotlib + MNE).",
        "description_es": "Herramientas para visualizar conectividad cerebral, topoplots y procesamiento EEG (Matplotlib + MNE).",
        "tools": ["Python", "Matplotlib", "NumPy", "Flask"],
        "documentation": "https://dunderlab.readthedocs.io/projects/Visualizations/en/latest/",
        "repository": "https://github.com/dunderlab/python-dunderlab.visualizations",
        "logo": "https://dunderlab.readthedocs.io/projects/Visualizations/en/latest/_images/conn.png",
        "year": "2019",
    },
    {
        "name": "Foundation",
        "type": "Python module",
        "type_es": "Módulo de Python",
        "description": "Utilities for managing Docker-based workers with a Radiant-based web interface.",
        "description_es": "Utilidades para gestionar workers basados en Docker con una interfaz web basada en Radiant.",
        "tools": ["Python", "Docker", "Django", "PostgreSQL"],
        "documentation": "",
        "repository": "https://github.com/dunderlab/python-dunderlab.foundation",
        "logo": "https://dunderlab-foundation.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2019",
    },
    {
        "name": "Matplotlib-FigureStream",
        "type": "Python module",
        "type_es": "Módulo de Python",
        "description": "Backend for serving Matplotlib animations as real-time JPEG streams through Flask.",
        "description_es": "Backend para servir animaciones de Matplotlib como flujos JPEG en tiempo real utilizando Flask.",
        "tools": ["Python", "Matplotlib", "NumPy", "Flask"],
        "documentation": "https://figurestream.readthedocs.io/en/latest/",
        "repository": "https://github.com/dunderlab/python-matplotlib-figurestream",
        "logo": "https://figurestream.readthedocs.io/en/latest/_static/logo.svg",
        "year": "2019",
    },
)
